apiVersion: v1
kind: Service
metadata:
  name: database-proxy
spec: 
  type: NodePort
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
  selector:
    app: mariadb
    service: database

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-proxy
  labels:
    app: mariadb
    service: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
      service: database
  template:
    metadata:
      labels:
        app: mariadb
        service: database
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.5.8
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
        - name: init-script
          mountPath: /tmp/init.sql
          subPath: init.sql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: secret
        args: ["--init-file", "/tmp/init.sql"]
        livenessProbe:
          exec:
            command: ["mysqladmin", "-uroot", "-p$MYSQL_ROOT_PASSWORD", "ping"]
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command: ["sh", "-ec", ">-", "mysql -h127.0.0.1 -uroot -p$MYSQL_ROOT_PASSWORD -e'SELECT 1'"]
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1

      volumes:
      - name: data
        emptyDir:
          medium: Memory
      - name: init-script
        secret:
          secretName: database-init-script
          items:
          - key: sql
            path: init.sql

