---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: fling
  labels:
    app: fling
    service: api

spec:
  replicas: 2
  selector:
    matchLabels:
      app: fling
      service: api
  template:
    metadata:
      labels:
        app: fling
        service: api
    spec:
      initContainers:
        - name: migrate-database
          imagePullPolicy: Always
          image: "flingemail/api:{{ api_version }}"
          command: ["sh", "-c", "php artisan migrate --force"]
          volumeMounts:
            - name: config-file
              mountPath: /var/www/.env
              subPath: .env

      containers:
        - name: web
          imagePullPolicy: Always
          image: "flingemail/api:{{ api_version }}"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-file
              mountPath: /var/www/.env
              subPath: .env
          readinessProbe:
            httpGet:
              path: /health
              port: 80

      volumes:
        - name: config-file
          secret:
            secretName: fling
            items:
              - key: apiEnv
                path: .env
