apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: fling-email-api

spec:
  rules:
  - host: {{ api_domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fling-email-api
            port:
              number: 80
