---
apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: fling-api

spec:
  rules:
    - host: "{{ api_domain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fling-api
                port:
                  number: 80
