apiVersion: networking.k8s.io/v1beta1
kind: Ingress

metadata:
  name: api

spec:
  rules:
  - host: {{ api_domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: api
          servicePort: 80
