---
apiVersion: v1
kind: Secret

metadata:
  name: fling

type: Opaque
stringData:
  apiEnv: |
    APP_NAME="Fling.email API"
    APP_ENV={{ environment }}
    APP_KEY={{ api_app_key }}
    APP_DEBUG={{ api_app_debug }}
    APP_URL={{ "http" if environment == "local" else "https" }}://{{ api_domain }}

    LOG_CHANNEL=stack

    DB_CONNECTION=mysql
    DB_HOST={{ api_database_host }}
    DB_PORT={{ api_database_port }}
    DB_DATABASE={{ api_database_name }}
    DB_USERNAME={{ api_database_username }}
    DB_PASSWORD={{ api_database_password }}

    QUEUE_CONNECTION=sync
